### ISSUE TITLE
Update to jaxlib 0.4.1 ?

### ISSUE THREAD

**Issue by adam-hartshorne** [cloudhan/jax-windows-builder#20]
This is a major update to JAX. Would be great to get this building with Windows. I have been struggling to manage to get to build myself locally.

**Comment by carlesoctav** [comment]
+1

**Comment by cloudhan** [comment]
It is not buildable due to recent change in tensorflow, or, precisely, openxla. There are various compiling and linking error due to source-level imcompatibility. They are undergoing tf->openxla translation, so it is not as easy as PR. I can locally produce a whl following: https://github.com/google/jax/issues/14466

**Comment by siwuxei** [comment]
+1

**Comment by cloudhan** [comment]
0.4.1 is not buildable, newer is provided
