### ISSUE TITLE
Link to builds is broken 

### ISSUE THREAD

**Issue by adam-hartshorne** [cloudhan/jax-windows-builder#3]
Link to https://whls.blob.core.windows.net/unstable/index.html is broken.

**Comment by cloudhan** [comment]
New version azure-cli is causing some uploading issue.

**Comment by cloudhan** [comment]
@oracle3001 can you check the link again? Due to the azure side change. Recent `index.html` do not have content-type automatically set, causing it being treated as standard file. Then a file download is performed. The `index.html` contains relative path, which in turn cause downloaded file refers to you local path. I switched to absolute link and manually set content-type on uploading.

It should be fixed now, please check and report back. If the browser still downloads the link as a file, try open it in privacy mode (Incognito for chrome)

**Comment by adam-hartshorne** [comment]
I can confirm it works now. Thank you.
